name: sync_menu_editor

on: workflow_dispatch

jobs:
  check-menu-editor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-node@v3
        with: 
          node-version: '18.x'
      - name: Sync Menu Editor    
        run: |
          npm install node-fetch
          git config user.email "adamfri@wix.com"
          git config user.name "Adam Friedmann"
          git checkout -b menu-editor-sync
          node scripts/getHiddenItems.mjs
          git add .
          DIFF=$(git status --porcelain)
          if [[ "$DIFF" == *"hidden-items.json"* ]]; then
            node scripts/buildDevPreviewList.mjs
            git add .
            git commit -m "Syncing with hidden items in the menu editor"
            git push --set-upstream origin menu-editor-sync
            echo "changes_pushed=yes" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: slackapi/slack-github-action@v1.23.0
        if: ${{ env.changes_pushed == 'yes' }}
        with:
          payload: |
            {
              "branch_name" : "menu-editor-sync"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
